project:
  type: website

website:
  title: "DSE informal blog"
  navbar:
    left:
      - href: index.md
        text: Home
      - about.md

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



