[project]
authors = ["Matt Fisher <mfisher87@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "informal-blog"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
quarto = ">=1.6.42,<2"
